In [8]:
import pandas as pd 
import os

In [17]:
path="D:\\SelfProject\\iNeuron\\Python\\data\\sample-csv\\titanic.csv"
os.path.relpath(path)

'data\\sample-csv\\titanic.csv'

In [10]:
# Files :
    
#     sample csv file - https://github.com/codeforamerica/ohana-api/tree/master/data/sample-csv
#     Titanic - https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
#     excel file - https://github.com/finbourne/sample-excel

In [11]:
ls

 Volume in drive D is New Volume
 Volume Serial Number is F8E2-D371

 Directory of d:\SelfProject\iNeuron\Python

04-02-2026  00:54    <DIR>          .
04-04-2023  00:17    <DIR>          ..
04-02-2026  00:42    <DIR>          .git
04-04-2023  00:18    <DIR>          .ipynb_checkpoints
04-04-2023  00:17            23,057 000.python basic.ipynb
04-04-2023  00:17            23,471 001.python basic.ipynb
04-04-2023  00:17            16,952 002.whileloop.ipynb
04-04-2023  00:17            17,533 003.Forloop.ipynb
04-04-2023  00:17            39,935 004.python string and list manupulation.ipynb
04-04-2023  00:17            69,090 004.python string and list manupulation-nov.ipynb
04-04-2023  00:17            56,644 005.list manupulaton.ipynb
04-04-2023  00:17            54,898 006.TUPLE SET AND DICT-bckup.ipynb
04-04-2023  00:17            59,358 006.Tuples , set , dict .ipynb
04-04-2023  00:17            27,917 007.Function in pyton  (1).ipynb
04-04-2023  00:17         9,562,697 008.Function and files.ipynb
04-04-2023  00:17            23,880 009.logging and debuging.ipynb
04-04-2023  00:17            28,817 010.class and object.ipynb
04-04-2023  00:17            16,784 011.file sysetm.ipynb
04-04-2023  00:17        21,685,762 012.iterator generator.ipynb
04-04-2023  00:17            10,152 013.Exception handling class 1.ipynb
04-04-2023  00:17            31,318 014.Exception handling class 2 (1).ipynb
04-04-2023  00:17             4,010 015.logging (1).ipynb
04-04-2023  00:17             4,053 016.logging (1).ipynb
04-04-2023  00:17            33,508 017.oops class 1.ipynb
04-04-2023  00:17            39,947 018.oops 29th .ipynb
04-04-2023  00:17            41,225 019.oops 30th.ipynb
04-04-2023  00:17            38,986 020.oops 2 (2).ipynb
04-04-2023  00:17            48,670 021.if else , for loop.ipynb
04-04-2023  00:17            25,286 022.for loops while loop.ipynb
04-04-2023  00:17            49,806 023.practice problem python basic.ipynb
04-04-2023  00:17            11,903 024.glass.data
03-02-2026  21:56            93,103 025.SQL basic.ipynb
04-04-2023  00:17           201,080 026.sql day 2.ipynb
04-02-2026  00:23            52,634 027.mongodb class 1.ipynb
04-02-2026  00:54            58,908 028.SQLLITE ,map ,reduce ,filter,zip.ipynb
04-04-2023  00:17           370,969 029.Pandas.ipynb
04-04-2023  00:17           543,374 031.pandas day 2.ipynb
04-04-2023  00:17           131,595 032.pandas class 3.ipynb
04-04-2023  00:17           162,010 033.pandas 4.ipynb
04-04-2023  00:17           265,557 034.pandas class homework discussed.ipynb
04-04-2023  00:17            78,420 035.pandas and numpy.ipynb
04-04-2023  00:17            32,657 036.numpy day 2.ipynb
04-04-2023  00:17            60,118 036.numpy_recorded.ipynb
04-04-2023  00:17         2,865,371 037.Graph.ipynb
04-04-2023  00:17           828,686 038.graphs day 2.ipynb
04-04-2023  00:17         1,113,578 039.plotly.ipynb
04-04-2023  00:17            34,222 4.Control Flow.ipynb
04-02-2026  00:14    <DIR>          data
04-02-2026  00:43             8,192 ineuron.db
04-02-2026  00:44            12,288 jobdb.db
04-02-2026  00:54            12,288 jobsdb.db
04-04-2023  00:17                 0 OOPS.log
04-02-2026  00:43             8,192 person.db
04-04-2023  00:17                36 README.md
03-02-2026  23:21             5,402 SUMMARY.md
              50 File(s)     38,984,339 bytes
               5 Dir(s)  363,010,732,032 bytes free

In [12]:
pd.read_csv('.\data\sample-csv\phones.csv')

,id,contact_id,location_id,organization_id,service_id,country_prefix,department,extension,number,number_type,vanity_number
0,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 780-7525,voice,NaN
1,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 701-0856,fax,NaN
2,3,NaN,2.0,NaN,NaN,NaN,NaN,4385.0,650 403-4300,voice,NaN
3,4,NaN,2.0,NaN,NaN,NaN,NaN,NaN,650 403-4302,fax,NaN
4,5,NaN,3.0,NaN,NaN,NaN,English,NaN,650 403-4300,voice,NaN
5,6,NaN,3.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
6,7,NaN,4.0,NaN,NaN,NaN,NaN,4500.0,650 403-4300,voice,NaN
7,8,NaN,4.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
8,9,NaN,5.0,NaN,NaN,NaN,NaN,4100.0,650 403-4300,voice,NaN
9,10,NaN,5.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
10,11,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-2025,voice,NaN
11,12,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
12,13,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-0126,voice,NaN
13,14,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-4067,fax,NaN
14,15,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 323-2022,voice,NaN
15,16,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
16,17,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 780-7261,voice,NaN
17,18,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 569-3371,fax,NaN
18,19,NaN,10.0,NaN,NaN,NaN,Circulation,NaN,650 780-7018,voice,NaN
19,20,NaN,10.0,NaN,NaN,NaN,NaN,NaN,650 780-7069,fax,NaN
20,21,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 780-7010,voice,NaN
21,23,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7077,voice,NaN
22,24,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7004,fax,NaN
23,25,NaN,13.0,NaN,NaN,NaN,NaN,NaN,650 780-5740,voice,NaN
24,26,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 368-4643,voice,NaN
25,27,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 364-1712,fax,NaN
26,28,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 643-8000,voice,NaN
27,29,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 285-1391,fax,NaN
28,30,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-0420,voice,NaN
29,31,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-8075,fax,NaN
30,32,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4591,voice,NaN
31,33,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-2594,fax,NaN
32,34,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4594,fax,NaN
33,35,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1447,voice,NaN
34,36,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1457,fax,NaN
35,37,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0400,voice,NaN
36,38,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0440,fax,NaN
37,39,NaN,21.0,NaN,NaN,NaN,CalFresh,1223.0,7035551212,voice,703-555-ABCD
38,40,NaN,21.0,NaN,NaN,NaN,CalFresh,NaN,2025551212,fax,NaN
39,41,29.0,NaN,NaN,NaN,1.0,Referrals,1200.0,123-456-7890,voice,NaN
40,42,29.0,NaN,NaN,NaN,1.0,Referrals,NaN,202-555-1212,fax,NaN
41,43,NaN,22.0,NaN,NaN,NaN,Information,123.0,650 372-6200,voice,222-555-INFO
42,44,NaN,22.0,NaN,NaN,NaN,Reservations,NaN,650 627-8244,fax,NaN
43,45,NaN,22.0,NaN,NaN,NaN,Hotline,NaN,800 372-6200,hotline,NaN
44,46,NaN,22.0,NaN,NaN,NaN,Rental Assistance,202.0,650 372-6200,tty,NaN
45,52,36.0,NaN,NaN,NaN,NaN,CalFresh Applications,123.0,703-555-1212,voice,NaN
46,53,NaN,NaN,8.0,NaN,NaN,Operations,101.0,123-456-7890,voice,NaN
47,54,32.0,NaN,NaN,NaN,NaN,Operations,NaN,703-444-1234,fax,NaN
48,55,32.0,NaN,NaN,NaN,NaN,Operations,101.0,650-555-1212,voice,NaN
49,56,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 365-3738,fax,NaN
50,57,NaN,NaN,NaN,22.0,NaN,Passport Photos,123.0,123-456-7890,voice,NaN
51,58,NaN,NaN,NaN,22.0,NaN,Passport Photos Fax,NaN,789-456-1230,fax,NaN
52,59,NaN,NaN,NaN,22.0,NaN,Passport Help via SMS,NaN,650-222-5555,sms,NaN
53,60,29.0,NaN,NaN,NaN,NaN,NaN,NaN,650-555-1212,sms,NaN

In [13]:
pd.read_csv(r'.\data\sample-csv\titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
pd.read_csv('.\data\sample-csv\services.csv')

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
# pd.read_csv('.\data\sample-csv\taxonomy.csv')
# \t → means TAB character

# \s → invalid escape

# \d → invalid escape
pd.read_csv('.\data\sample-csv\programs.csv')

   id  organization_id           name  alternate_name
0   1                1  Defeat Hunger             NaN

In [29]:
# df = pd.read_csv('taxonomy.csv')
df = pd.read_csv(r'.\data\sample-csv\taxonomy.csv')

In [31]:
a = 1

In [32]:
type(a)

int

In [33]:
type(df)

pandas.core.frame.DataFrame

In [34]:
ls

 Volume in drive D is New Volume
 Volume Serial Number is F8E2-D371

 Directory of d:\SelfProject\iNeuron\Python

04-02-2026  00:54    <DIR>          .
04-04-2023  00:17    <DIR>          ..
04-02-2026  00:42    <DIR>          .git
04-04-2023  00:18    <DIR>          .ipynb_checkpoints
04-04-2023  00:17            23,057 000.python basic.ipynb
04-04-2023  00:17            23,471 001.python basic.ipynb
04-04-2023  00:17            16,952 002.whileloop.ipynb
04-04-2023  00:17            17,533 003.Forloop.ipynb
04-04-2023  00:17            39,935 004.python string and list manupulation.ipynb
04-04-2023  00:17            69,090 004.python string and list manupulation-nov.ipynb
04-04-2023  00:17            56,644 005.list manupulaton.ipynb
04-04-2023  00:17            54,898 006.TUPLE SET AND DICT-bckup.ipynb
04-04-2023  00:17            59,358 006.Tuples , set , dict .ipynb
04-04-2023  00:17            27,917 007.Function in pyton  (1).ipynb
04-04-2023  00:17         9,562,697 008.Function and files.ipynb
04-04-2023  00:17            23,880 009.logging and debuging.ipynb
04-04-2023  00:17            28,817 010.class and object.ipynb
04-04-2023  00:17            16,784 011.file sysetm.ipynb
04-04-2023  00:17        21,685,762 012.iterator generator.ipynb
04-04-2023  00:17            10,152 013.Exception handling class 1.ipynb
04-04-2023  00:17            31,318 014.Exception handling class 2 (1).ipynb
04-04-2023  00:17             4,010 015.logging (1).ipynb
04-04-2023  00:17             4,053 016.logging (1).ipynb
04-04-2023  00:17            33,508 017.oops class 1.ipynb
04-04-2023  00:17            39,947 018.oops 29th .ipynb
04-04-2023  00:17            41,225 019.oops 30th.ipynb
04-04-2023  00:17            38,986 020.oops 2 (2).ipynb
04-04-2023  00:17            48,670 021.if else , for loop.ipynb
04-04-2023  00:17            25,286 022.for loops while loop.ipynb
04-04-2023  00:17            49,806 023.practice problem python basic.ipynb
04-04-2023  00:17            11,903 024.glass.data
03-02-2026  21:56            93,103 025.SQL basic.ipynb
04-04-2023  00:17           201,080 026.sql day 2.ipynb
04-02-2026  00:23            52,634 027.mongodb class 1.ipynb
04-02-2026  00:54            58,908 028.SQLLITE ,map ,reduce ,filter,zip.ipynb
04-04-2023  00:17           370,969 029.Pandas.ipynb
04-04-2023  00:17           543,374 031.pandas day 2.ipynb
04-04-2023  00:17           131,595 032.pandas class 3.ipynb
04-04-2023  00:17           162,010 033.pandas 4.ipynb
04-04-2023  00:17           265,557 034.pandas class homework discussed.ipynb
04-04-2023  00:17            78,420 035.pandas and numpy.ipynb
04-04-2023  00:17            32,657 036.numpy day 2.ipynb
04-04-2023  00:17            60,118 036.numpy_recorded.ipynb
04-04-2023  00:17         2,865,371 037.Graph.ipynb
04-04-2023  00:17           828,686 038.graphs day 2.ipynb
04-04-2023  00:17         1,113,578 039.plotly.ipynb
04-04-2023  00:17            34,222 4.Control Flow.ipynb
04-02-2026  00:14    <DIR>          data
04-02-2026  00:43             8,192 ineuron.db
04-02-2026  00:44            12,288 jobdb.db
04-02-2026  00:54            12,288 jobsdb.db
04-04-2023  00:17                 0 OOPS.log
04-02-2026  00:43             8,192 person.db
04-04-2023  00:17                36 README.md
03-02-2026  23:21             5,402 SUMMARY.md
              50 File(s)     38,984,339 bytes
               5 Dir(s)  363,010,732,032 bytes free

In [35]:
pd.read_csv('.\data\sample-csv\mail_addresses.csv',header=None)

,0,1,2,3,4,5,6,7,8
0,id,location_id,attention,address_1,address_2,city,state_province,postal_code,country
1,1,1,Fair Oaks Intergenerational Center,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
2,2,2,PFS Second Career Services,24 Second Avenue,NaN,San Mateo,CA,94401,US
3,3,3,PFS Senior Peer Counseling,24 Second Avenue,NaN,San Mateo,CA,94403,US
4,4,4,PFS Family Visitation Center,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,5,5,Economic Self - Sufficiency Program,24 Second Avenue,NaN,San Mateo,CA,94401,US
6,6,6,Little House,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
7,7,7,Rosener House,500 Arbor Road,NaN,Menlo Park,CA,94025,US
8,8,8,Meals on Wheels - South County,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
9,9,9,Fair Oaks Branch,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
10,10,10,Main Library,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
11,11,11,Schaberg Branch,2140 Euclid Avenue,NaN,Redwood City,CA,94061,US
12,12,12,Project Read,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
13,13,13,Redwood Shores Branch,399 Marine Parkway,NaN,Redwood City,CA,94065,US
14,14,14,Salvation Army,P.O. Box 1147,NaN,Redwood City,CA,94064,US
15,15,15,Adult Rehabilitation Center,1500 Valencia Street,NaN,San Francisco,CA,94110,US
16,16,16,Salvation Army,P.O. Box 61868,NaN,Sunnyvale,CA,94088,US
17,17,17,Salvation Army,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
18,18,18,Redwood City Free Medical Clinic,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
19,19,19,San Mateo Free Medical/Dental,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
20,20,20,NaN,123 Main Street,NaN,Fairfax,VA,22031,US
21,21,22,The Foodies,2013 Avenue of the fellows,Suite 100,San Francisco,CA,90210,US

In [36]:
pd.read_csv('.\data\sample-csv\mail_addresses.csv' ,names=["adfgfadssaf" , 'b' , 'c' , 'd' , "fdsfsa" , "fsdf" ,"fdsfs"] )

,,adfgfadssaf,b,c,d,fdsfsa,fsdf,fdsfs
id,location_id,attention,address_1,address_2,city,state_province,postal_code,country
1,1,Fair Oaks Intergenerational Center,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
2,2,PFS Second Career Services,24 Second Avenue,NaN,San Mateo,CA,94401,US
3,3,PFS Senior Peer Counseling,24 Second Avenue,NaN,San Mateo,CA,94403,US
4,4,PFS Family Visitation Center,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,5,Economic Self - Sufficiency Program,24 Second Avenue,NaN,San Mateo,CA,94401,US
6,6,Little House,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
7,7,Rosener House,500 Arbor Road,NaN,Menlo Park,CA,94025,US
8,8,Meals on Wheels - South County,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
9,9,Fair Oaks Branch,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
10,10,Main Library,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
11,11,Schaberg Branch,2140 Euclid Avenue,NaN,Redwood City,CA,94061,US
12,12,Project Read,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
13,13,Redwood Shores Branch,399 Marine Parkway,NaN,Redwood City,CA,94065,US
14,14,Salvation Army,P.O. Box 1147,NaN,Redwood City,CA,94064,US
15,15,Adult Rehabilitation Center,1500 Valencia Street,NaN,San Francisco,CA,94110,US
16,16,Salvation Army,P.O. Box 61868,NaN,Sunnyvale,CA,94088,US
17,17,Salvation Army,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
18,18,Redwood City Free Medical Clinic,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
19,19,San Mateo Free Medical/Dental,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
20,20,NaN,123 Main Street,NaN,Fairfax,VA,22031,US
21,22,The Foodies,2013 Avenue of the fellows,Suite 100,San Francisco,CA,90210,US

In [37]:
pd.read_csv('.\data\sample-csv\mail_addresses.csv' ,names=["adfgfadssaf" , 'b' ] )

,,,,,,,adfgfadssaf,b
id,location_id,attention,address_1,address_2,city,state_province,postal_code,country
1,1,Fair Oaks Intergenerational Center,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
2,2,PFS Second Career Services,24 Second Avenue,NaN,San Mateo,CA,94401,US
3,3,PFS Senior Peer Counseling,24 Second Avenue,NaN,San Mateo,CA,94403,US
4,4,PFS Family Visitation Center,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,5,Economic Self - Sufficiency Program,24 Second Avenue,NaN,San Mateo,CA,94401,US
6,6,Little House,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
7,7,Rosener House,500 Arbor Road,NaN,Menlo Park,CA,94025,US
8,8,Meals on Wheels - South County,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
9,9,Fair Oaks Branch,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
10,10,Main Library,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
11,11,Schaberg Branch,2140 Euclid Avenue,NaN,Redwood City,CA,94061,US
12,12,Project Read,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
13,13,Redwood Shores Branch,399 Marine Parkway,NaN,Redwood City,CA,94065,US
14,14,Salvation Army,P.O. Box 1147,NaN,Redwood City,CA,94064,US
15,15,Adult Rehabilitation Center,1500 Valencia Street,NaN,San Francisco,CA,94110,US
16,16,Salvation Army,P.O. Box 61868,NaN,Sunnyvale,CA,94088,US
17,17,Salvation Army,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
18,18,Redwood City Free Medical Clinic,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
19,19,San Mateo Free Medical/Dental,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
20,20,NaN,123 Main Street,NaN,Fairfax,VA,22031,US
21,22,The Foodies,2013 Avenue of the fellows,Suite 100,San Francisco,CA,90210,US

In [44]:
pd.read_csv('.\data\sample-csv\contacts.csv')

,id,location_id,organization_id,service_id,name,title,email,department
0,1,1.0,NaN,NaN,Susan Houston,Director of Older Adult Services,NaN,NaN
1,2,1.0,NaN,NaN,Christina Gonzalez,Center Director,NaN,NaN
2,3,2.0,NaN,NaN,Brenda Brown,"Director, Second Career Services",NaN,NaN
3,4,3.0,NaN,NaN,"Howard Lader, LCSW","Manager, Senior Peer Counseling",NaN,NaN
4,5,4.0,NaN,NaN,Kimberly Pesavento,Director of Visitation,NaN,NaN
5,6,5.0,NaN,NaN,Joe Bloom,Financial Empowerment Programs Program Director,NaN,NaN
6,7,6.0,NaN,NaN,Peter Olson,Little House Director,NaN,NaN
7,8,6.0,NaN,NaN,Bart Charlow,"Executive Director, Peninsula Volunteers",NaN,NaN
8,9,7.0,NaN,NaN,Bart Charlow,"Executive Director, Peninsula Volunteers",NaN,NaN
9,10,7.0,NaN,NaN,Barbara Kalt,Director,NaN,NaN
10,11,8.0,NaN,NaN,Marilyn Baker-Venturini,Director,NaN,NaN
11,12,8.0,NaN,NaN,Graciela Hernandez,Assistant Manager,NaN,NaN
12,13,8.0,NaN,NaN,Julie Avelino,Assessment Specialist,NaN,NaN
13,14,9.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
14,15,9.0,NaN,NaN,Maria Kramer,Library Divisions Manager,NaN,NaN
15,16,10.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
16,17,10.0,NaN,NaN,Maria Kramer,Library Division Manager,NaN,NaN
17,18,11.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
18,19,11.0,NaN,NaN,Elizabeth Meeks,Branch Manager,NaN,NaN
19,20,12.0,NaN,NaN,Kathy Endaya,Director,NaN,NaN
20,21,13.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
21,22,14.0,NaN,NaN,Andres Espinoza,"Captain, Commanding Officer",NaN,NaN
22,23,15.0,NaN,NaN,Jack Phillips,Administrator,NaN,NaN
23,24,16.0,NaN,NaN,James Lee,Commanding Officer,NaN,NaN
24,25,17.0,NaN,NaN,Kenneth Gibson,Major,NaN,NaN
25,26,18.0,NaN,NaN,Sharon Petersen,Administrator,NaN,NaN
26,27,19.0,NaN,NaN,Sharon Petersen,Administrator,NaN,NaN
27,28,21.0,NaN,NaN,Moncef,NaN,NaN,Office of Innovation
28,29,22.0,NaN,NaN,Suzanne Badenhoop,Board President,suzanne@example.com,Referrals
29,32,NaN,8.0,NaN,Elizabeth Feeney,CEO,e.feeney@foobar.org,Operations
30,36,NaN,NaN,22.0,Joe Smith,CalFresh Specialist,john.smith@example.org,CalFresh Applications

In [ ]:
pd.read_csv('.\data\sample-csv\contacts.csv',sep='@')
# You forced the wrong separator
# Most CSV files use:

# comma ,

# tab \t

# semicolon ; pipe |

SyntaxError: invalid syntax (Temp/ipykernel_13476/3744588874.py, line 2)

In [45]:
df = pd.read_csv('.\data\sample-csv\contacts.csv',sep='|')

In [46]:
df

   id,location_id,organization_id,service_id,name,title,email,department
0   1,1,,,Susan Houston,Director of Older Adult Se...
1          2,1,,,Christina Gonzalez,Center Director,,
2   3,2,,,Brenda Brown,"Director, Second Career Se...
3   4,3,,,"Howard Lader, LCSW","Manager, Senior Pe...
4   5,4,,,Kimberly Pesavento,Director of Visitation,,
5   6,5,,,Joe Bloom,Financial Empowerment Programs...
6           7,6,,,Peter Olson,Little House Director,,
7   8,6,,,Bart Charlow,"Executive Director, Penins...
8   9,7,,,Bart Charlow,"Executive Director, Penins...
9                      10,7,,,Barbara Kalt,Director,,
10          11,8,,,Marilyn Baker-Venturini,Director,,
11      12,8,,,Graciela Hernandez,Assistant Manager,,
12       13,8,,,Julie Avelino,Assessment Specialist,,
13              14,9,,,Dave Genesy,Library Director,,
14    15,9,,,Maria Kramer,Library Divisions Manager,,
15             16,10,,,Dave Genesy,Library Director,,
16    17,10,,,Maria Kramer,Library Division Manager,,
17             18,11,,,Dave Genesy,Library Director,,
18           19,11,,,Elizabeth Meeks,Branch Manager,,
19                    20,12,,,Kathy Endaya,Director,,
20             21,13,,,Dave Genesy,Library Director,,
21  22,14,,,Andres Espinoza,"Captain, Commanding O...
22              23,15,,,Jack Phillips,Administrator,,
23             24,16,,,James Lee,Commanding Officer,,
24                     25,17,,,Kenneth Gibson,Major,,
25            26,18,,,Sharon Petersen,Administrator,,
26            27,19,,,Sharon Petersen,Administrator,,
27              28,21,,,Moncef,,,Office of Innovation
28  29,22,,,Suzanne Badenhoop,Board President,suza...
29  32,,8,,Elizabeth Feeney,CEO,e.feeney@foobar.or...
30  36,,,22,Joe Smith,CalFresh Specialist,john.smi...

In [47]:
pd.read_csv('.\data\sample-csv\contacts.csv',sep='|' , skiprows=[1,3])

   id,location_id,organization_id,service_id,name,title,email,department
0          2,1,,,Christina Gonzalez,Center Director,,
1   4,3,,,"Howard Lader, LCSW","Manager, Senior Pe...
2   5,4,,,Kimberly Pesavento,Director of Visitation,,
3   6,5,,,Joe Bloom,Financial Empowerment Programs...
4           7,6,,,Peter Olson,Little House Director,,
5   8,6,,,Bart Charlow,"Executive Director, Penins...
6   9,7,,,Bart Charlow,"Executive Director, Penins...
7                      10,7,,,Barbara Kalt,Director,,
8           11,8,,,Marilyn Baker-Venturini,Director,,
9       12,8,,,Graciela Hernandez,Assistant Manager,,
10       13,8,,,Julie Avelino,Assessment Specialist,,
11              14,9,,,Dave Genesy,Library Director,,
12    15,9,,,Maria Kramer,Library Divisions Manager,,
13             16,10,,,Dave Genesy,Library Director,,
14    17,10,,,Maria Kramer,Library Division Manager,,
15             18,11,,,Dave Genesy,Library Director,,
16           19,11,,,Elizabeth Meeks,Branch Manager,,
17                    20,12,,,Kathy Endaya,Director,,
18             21,13,,,Dave Genesy,Library Director,,
19  22,14,,,Andres Espinoza,"Captain, Commanding O...
20              23,15,,,Jack Phillips,Administrator,,
21             24,16,,,James Lee,Commanding Officer,,
22                     25,17,,,Kenneth Gibson,Major,,
23            26,18,,,Sharon Petersen,Administrator,,
24            27,19,,,Sharon Petersen,Administrator,,
25              28,21,,,Moncef,,,Office of Innovation
26  29,22,,,Suzanne Badenhoop,Board President,suza...
27  32,,8,,Elizabeth Feeney,CEO,e.feeney@foobar.or...
28  36,,,22,Joe Smith,CalFresh Specialist,john.smi...

In [48]:
df1 = pd.read_csv('.\data\sample-csv\contacts.csv',sep='|' , skiprows=[1,3])

In [49]:
df1

   id,location_id,organization_id,service_id,name,title,email,department
0          2,1,,,Christina Gonzalez,Center Director,,
1   4,3,,,"Howard Lader, LCSW","Manager, Senior Pe...
2   5,4,,,Kimberly Pesavento,Director of Visitation,,
3   6,5,,,Joe Bloom,Financial Empowerment Programs...
4           7,6,,,Peter Olson,Little House Director,,
5   8,6,,,Bart Charlow,"Executive Director, Penins...
6   9,7,,,Bart Charlow,"Executive Director, Penins...
7                      10,7,,,Barbara Kalt,Director,,
8           11,8,,,Marilyn Baker-Venturini,Director,,
9       12,8,,,Graciela Hernandez,Assistant Manager,,
10       13,8,,,Julie Avelino,Assessment Specialist,,
11              14,9,,,Dave Genesy,Library Director,,
12    15,9,,,Maria Kramer,Library Divisions Manager,,
13             16,10,,,Dave Genesy,Library Director,,
14    17,10,,,Maria Kramer,Library Division Manager,,
15             18,11,,,Dave Genesy,Library Director,,
16           19,11,,,Elizabeth Meeks,Branch Manager,,
17                    20,12,,,Kathy Endaya,Director,,
18             21,13,,,Dave Genesy,Library Director,,
19  22,14,,,Andres Espinoza,"Captain, Commanding O...
20              23,15,,,Jack Phillips,Administrator,,
21             24,16,,,James Lee,Commanding Officer,,
22                     25,17,,,Kenneth Gibson,Major,,
23            26,18,,,Sharon Petersen,Administrator,,
24            27,19,,,Sharon Petersen,Administrator,,
25              28,21,,,Moncef,,,Office of Innovation
26  29,22,,,Suzanne Badenhoop,Board President,suza...
27  32,,8,,Elizabeth Feeney,CEO,e.feeney@foobar.or...
28  36,,,22,Joe Smith,CalFresh Specialist,john.smi...

In [50]:
df = pd.read_csv('.\data\sample-csv\services.csv')

In [51]:
type(df)

pandas.core.frame.DataFrame

In [52]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [53]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [54]:
df.head(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [55]:
df.tail(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [56]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [57]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [58]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [59]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [60]:
a = df["name"]

In [61]:
type(a)

pandas.core.series.Series

In [62]:
df1 = df[["name" ,'location_id','id' ]]

In [63]:
type(df1)

pandas.core.frame.DataFrame

In [64]:
type(df[['name']])

pandas.core.frame.DataFrame

In [65]:
ls

 Volume in drive D is New Volume
 Volume Serial Number is F8E2-D371

 Directory of d:\SelfProject\iNeuron\Python

04-02-2026  00:54    <DIR>          .
04-04-2023  00:17    <DIR>          ..
04-02-2026  00:42    <DIR>          .git
04-04-2023  00:18    <DIR>          .ipynb_checkpoints
04-04-2023  00:17            23,057 000.python basic.ipynb
04-04-2023  00:17            23,471 001.python basic.ipynb
04-04-2023  00:17            16,952 002.whileloop.ipynb
04-04-2023  00:17            17,533 003.Forloop.ipynb
04-04-2023  00:17            39,935 004.python string and list manupulation.ipynb
04-04-2023  00:17            69,090 004.python string and list manupulation-nov.ipynb
04-04-2023  00:17            56,644 005.list manupulaton.ipynb
04-04-2023  00:17            54,898 006.TUPLE SET AND DICT-bckup.ipynb
04-04-2023  00:17            59,358 006.Tuples , set , dict .ipynb
04-04-2023  00:17            27,917 007.Function in pyton  (1).ipynb
04-04-2023  00:17         9,562,697 008.Function and files.ipynb
04-04-2023  00:17            23,880 009.logging and debuging.ipynb
04-04-2023  00:17            28,817 010.class and object.ipynb
04-04-2023  00:17            16,784 011.file sysetm.ipynb
04-04-2023  00:17        21,685,762 012.iterator generator.ipynb
04-04-2023  00:17            10,152 013.Exception handling class 1.ipynb
04-04-2023  00:17            31,318 014.Exception handling class 2 (1).ipynb
04-04-2023  00:17             4,010 015.logging (1).ipynb
04-04-2023  00:17             4,053 016.logging (1).ipynb
04-04-2023  00:17            33,508 017.oops class 1.ipynb
04-04-2023  00:17            39,947 018.oops 29th .ipynb
04-04-2023  00:17            41,225 019.oops 30th.ipynb
04-04-2023  00:17            38,986 020.oops 2 (2).ipynb
04-04-2023  00:17            48,670 021.if else , for loop.ipynb
04-04-2023  00:17            25,286 022.for loops while loop.ipynb
04-04-2023  00:17            49,806 023.practice problem python basic.ipynb
04-04-2023  00:17            11,903 024.glass.data
03-02-2026  21:56            93,103 025.SQL basic.ipynb
04-04-2023  00:17           201,080 026.sql day 2.ipynb
04-02-2026  00:23            52,634 027.mongodb class 1.ipynb
04-02-2026  00:54            58,908 028.SQLLITE ,map ,reduce ,filter,zip.ipynb
04-04-2023  00:17           370,969 029.Pandas.ipynb
04-04-2023  00:17           543,374 031.pandas day 2.ipynb
04-04-2023  00:17           131,595 032.pandas class 3.ipynb
04-04-2023  00:17           162,010 033.pandas 4.ipynb
04-04-2023  00:17           265,557 034.pandas class homework discussed.ipynb
04-04-2023  00:17            78,420 035.pandas and numpy.ipynb
04-04-2023  00:17            32,657 036.numpy day 2.ipynb
04-04-2023  00:17            60,118 036.numpy_recorded.ipynb
04-04-2023  00:17         2,865,371 037.Graph.ipynb
04-04-2023  00:17           828,686 038.graphs day 2.ipynb
04-04-2023  00:17         1,113,578 039.plotly.ipynb
04-04-2023  00:17            34,222 4.Control Flow.ipynb
04-02-2026  00:14    <DIR>          data
04-02-2026  00:43             8,192 ineuron.db
04-02-2026  00:44            12,288 jobdb.db
04-02-2026  00:54            12,288 jobsdb.db
04-04-2023  00:17                 0 OOPS.log
04-02-2026  00:43             8,192 person.db
04-04-2023  00:17                36 README.md
03-02-2026  23:21             5,402 SUMMARY.md
              50 File(s)     38,984,339 bytes
               5 Dir(s)  363,010,732,032 bytes free

In [66]:
pd.read_excel('.\data\sample-excel\LUSID Excel - Manage Orders.xlsx',sheet_name = "Allocations")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,This sheet allows you to manage Allocations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. ListAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. GetAllocation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. UpsertAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,MyAllocation001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,MyAllocation002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df = pd.read_excel('.\data\sample-excel\LUSID Excel - Manage Orders.xlsx')

In [68]:
df.keys()

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18'],
      dtype='object')

In [69]:
df = pd.ExcelFile('.\data\sample-excel\LUSID Excel - Manage Orders.xlsx')

In [70]:
df.sheet_names

['Executions', 'Orders', 'Allocations', 'Placements', 'Blocks']

In [71]:
for i in df.sheet_names:
    pd.read_excel('.\data\sample-excel\LUSID Excel - Manage Orders.xlsx' , sheet_name=i)

In [72]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [73]:
pd.read_csv('https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/phones.csv')

,id,contact_id,location_id,organization_id,service_id,country_prefix,department,extension,number,number_type,vanity_number
0,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 780-7525,voice,NaN
1,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 701-0856,fax,NaN
2,3,NaN,2.0,NaN,NaN,NaN,NaN,4385.0,650 403-4300,voice,NaN
3,4,NaN,2.0,NaN,NaN,NaN,NaN,NaN,650 403-4302,fax,NaN
4,5,NaN,3.0,NaN,NaN,NaN,English,NaN,650 403-4300,voice,NaN
5,6,NaN,3.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
6,7,NaN,4.0,NaN,NaN,NaN,NaN,4500.0,650 403-4300,voice,NaN
7,8,NaN,4.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
8,9,NaN,5.0,NaN,NaN,NaN,NaN,4100.0,650 403-4300,voice,NaN
9,10,NaN,5.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
10,11,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-2025,voice,NaN
11,12,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
12,13,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-0126,voice,NaN
13,14,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-4067,fax,NaN
14,15,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 323-2022,voice,NaN
15,16,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
16,17,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 780-7261,voice,NaN
17,18,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 569-3371,fax,NaN
18,19,NaN,10.0,NaN,NaN,NaN,Circulation,NaN,650 780-7018,voice,NaN
19,20,NaN,10.0,NaN,NaN,NaN,NaN,NaN,650 780-7069,fax,NaN
20,21,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 780-7010,voice,NaN
21,23,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7077,voice,NaN
22,24,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7004,fax,NaN
23,25,NaN,13.0,NaN,NaN,NaN,NaN,NaN,650 780-5740,voice,NaN
24,26,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 368-4643,voice,NaN
25,27,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 364-1712,fax,NaN
26,28,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 643-8000,voice,NaN
27,29,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 285-1391,fax,NaN
28,30,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-0420,voice,NaN
29,31,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-8075,fax,NaN
30,32,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4591,voice,NaN
31,33,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-2594,fax,NaN
32,34,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4594,fax,NaN
33,35,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1447,voice,NaN
34,36,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1457,fax,NaN
35,37,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0400,voice,NaN
36,38,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0440,fax,NaN
37,39,NaN,21.0,NaN,NaN,NaN,CalFresh,1223.0,7035551212,voice,703-555-ABCD
38,40,NaN,21.0,NaN,NaN,NaN,CalFresh,NaN,2025551212,fax,NaN
39,41,29.0,NaN,NaN,NaN,1.0,Referrals,1200.0,123-456-7890,voice,NaN
40,42,29.0,NaN,NaN,NaN,1.0,Referrals,NaN,202-555-1212,fax,NaN
41,43,NaN,22.0,NaN,NaN,NaN,Information,123.0,650 372-6200,voice,222-555-INFO
42,44,NaN,22.0,NaN,NaN,NaN,Reservations,NaN,650 627-8244,fax,NaN
43,45,NaN,22.0,NaN,NaN,NaN,Hotline,NaN,800 372-6200,hotline,NaN
44,46,NaN,22.0,NaN,NaN,NaN,Rental Assistance,202.0,650 372-6200,tty,NaN
45,52,36.0,NaN,NaN,NaN,NaN,CalFresh Applications,123.0,703-555-1212,voice,NaN
46,53,NaN,NaN,8.0,NaN,NaN,Operations,101.0,123-456-7890,voice,NaN
47,54,32.0,NaN,NaN,NaN,NaN,Operations,NaN,703-444-1234,fax,NaN
48,55,32.0,NaN,NaN,NaN,NaN,Operations,101.0,650-555-1212,voice,NaN
49,56,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 365-3738,fax,NaN
50,57,NaN,NaN,NaN,22.0,NaN,Passport Photos,123.0,123-456-7890,voice,NaN
51,58,NaN,NaN,NaN,22.0,NaN,Passport Photos Fax,NaN,789-456-1230,fax,NaN
52,59,NaN,NaN,NaN,22.0,NaN,Passport Help via SMS,NaN,650-222-5555,sms,NaN
53,60,29.0,NaN,NaN,NaN,NaN,NaN,NaN,650-555-1212,sms,NaN